.EXPORT_ALL_VARIABLES:
PRJ_DIR          ?= ..

SRC_LST          ?= sim_file_list.f

TST_TAR          ?= none
DSP_SETTING      ?= off
STP_ON_ERR       ?= local
DMP_SHM          ?= off
DMP_SHM_TIME     ?= 0
DMP_SHM_LEVEL    ?= AS
COV_TOP          ?= $(DUT_TOP)
BAK_SIM          ?= off

include ./makefile.mk
