.EXPORT_ALL_VARIABLES:
PRJ_DIR          ?= ..

DUT_TOP          ?= fft_top
SRC_LST          ?= file_list.f

TST_DIR          ?= tv
TST_TAR          ?= none
TST_TOP          ?= tb_$(DUT_TOP)
DSP_SETTING      ?= off
STP_ON_ERR       ?= local
DMP_SHM          ?= off
DMP_SHM_TIME     ?= 0
DMP_SHM_LEVEL    ?= AS
COV_TOP          ?= $(DUT_TOP)
BAK_SIM          ?= off

include ./makefile.mk
