.EXPORT_ALL_VARIABLES:
PRJ_DIR          ?= ..

DUT_TOP          ?= fft_top
SRC_LST          ?= file_list.f

SIM_TOP          ?= sim_$(DUT_TOP)
DSP_PRM          ?= off
STP_LVL          ?= local
DMP_SHM          ?= off
DMP_SHM_BGN      ?= 0
DMP_SHM_LVL      ?= AS
COV_TOP          ?= $(DUT_TOP)
BAK_SIM          ?= off

include ./makefile.mk
